language: python

script:
  - ./scripts/trigger_website_build.sh $TRAVIS_TOKEN

notifications:
  email:
    recipients:
      - emmanuel.thomas@tno.nl
      #- wilaw@akamai.com
    on_success: never # default: change
    on_failure: always # default: always
